/**
 * Edge Function Retirement Inventory — Source-of-truth audit snapshot.
 *
 * Audit date: 2026-07-28
 * Live Supabase project: fxkqgjakbyrxkmevkglv
 * Live inventory: 68 ACTIVE functions.
 *
 * This module is READ-ONLY documentation. It reflects the current live
 * `verify_jwt` flags and the auditor's classification of each function's
 * active source callers. `appliedLive` is false for every retirement
 * recommendation: no function has been retired to a 410 stub in this pass.
 *
 * Companion documents:
 *   - docs/security/EDGE_FUNCTION_AUDIT_2026-07-28.md (narrative + methodology)
 *   - src/lib/v2/legacyEndpoints.ts (previously-retired V1 payment slugs)
 */

export type Classification =
  | "required_v2"
  | "required_shared_account_auth"
  | "legacy_unreachable"
  | "already_410"
  | "unknown_review";

export type Disposition =
  | "keep"
  | "harden"
  | "retire_to_410"
  | "investigate";

export type AuthMechanism =
  | "platform_jwt"
  | "verifyAdmin_shared"
  | "service_secret"
  | "provider_signature"
  | "captcha_or_rate_limit"
  | "none"
  | "unknown";

export interface EdgeFunctionAuditEntry {
  /** Live Supabase function slug. */
  name: string;
  /** Live verify_jwt flag as reported by Supabase inventory. */
  verifyJwt: boolean;
  /** Current source-side auth mechanism. */
  authMechanism: AuthMechanism;
  /** Proven inbound callers or references (file paths). */
  callers: readonly string[];
  /** Outbound function-to-function or notable external dependencies. */
  outbound: readonly string[];
  /** One-line business purpose. */
  purpose: string;
  /** Matching V2 replacement slug, if any. */
  v2Replacement: string | null;
  /** Audit classification. */
  classification: Classification;
  /** Recommended disposition (documentation only — not yet applied). */
  disposition: Disposition;
  /** Whether the current recommendation has already been applied live. */
  appliedLive: false;
  /** Short rationale citing evidence. */
  evidence: string;
}

export const EDGE_FUNCTION_AUDIT_DATE = "2026-07-28" as const;

/** Slugs that are already HTTP 410 stubs in source or live. */
export const ALREADY_410_SLUGS = [
  "check-email-exists",
  "paypal-webhook",
  "resend-confirmation-email",
  "send-email-confirmation-reminder",
  "send-password-reset",
  "send-signup-confirmation",
  "track-email-engagement",
  "validate-signup",
  "verify-password-reset",
  "v2-qa-one-time-package-upload",
] as const;

export const EDGE_FUNCTION_AUDIT: readonly EdgeFunctionAuditEntry[] = [
  {
    name: "generate-metadata",
    verifyJwt: true,
    authMechanism: "platform_jwt",
    callers: [
      "src/pages/admin/components/prompts/components/AutoGenerateButton.tsx",
      "src/components/prompt-generator/TagsManager.tsx",
      "src/components/prompt-generator/SmartSuggestions.tsx",
    ],
    outbound: ["openai"],
    purpose: "AI: extract prompt metadata (tags, suggestions).",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "3 active src callers; verify_jwt=true covers auth.",
  },
  {
    name: "suggest-prompt",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [],
    outbound: ["openai"],
    purpose: "AI: suggest new prompts.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "harden",
    appliedLive: false,
    evidence:
      "No active src caller (test-only ref). Prior pass hardened with can_manage_prompts bearer auth; verify no legacy caller before retiring.",
  },
  {
    name: "get-all-users",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/pages/admin/components/users/hooks/useUserService.ts",
      "src/pages/admin/components/users/hooks/useUserBulkActions.ts",
      "src/pages/admin/components/users/components/ChangePasswordDialog.tsx",
    ],
    outbound: ["auth.admin"],
    purpose: "Admin user listing.",
    v2Replacement: "admin-users-v2",
    classification: "required_shared_account_auth",
    disposition: "keep",
    appliedLive: false,
    evidence: "3 active admin src callers; still reachable.",
  },
  {
    name: "get-image",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/components/ui/prompt-card/ImageWrapper.tsx"],
    outbound: ["storage"],
    purpose: "Image proxy (published resources, image MIME only).",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Hardened in prior pass; still called from prompt card.",
  },
  {
    name: "create-subscription",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/hooks/payment/helpers/subscriptionActivator.ts"],
    outbound: [],
    purpose: "V1 subscription creation.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "subscriptionActivator hook may be dead V1 code; needs route-graph confirmation before retiring.",
  },
  {
    name: "cancel-subscription",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/pages/admin/components/users/hooks/useUserService.ts"],
    outbound: [],
    purpose: "V1 subscription cancellation.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "One admin caller; V2 has no subscription surface.",
  },
  {
    name: "validate-file-upload",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/useSecureFileUpload.ts"],
    outbound: [],
    purpose: "Upload validation (V1 admin uploads).",
    v2Replacement: "v2-admin-upload-resource-file",
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "Referenced by useSecureFileUpload; confirm whether any V2 route reaches this hook.",
  },
  {
    name: "get-paypal-client-id",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: ["paypal"],
    purpose: "V1 PayPal client-id exposure.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "No active src caller; PayPal retired in V2.",
  },
  {
    name: "process-paypal-payment",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: ["paypal"],
    purpose: "V1 PayPal capture.",
    v2Replacement: "v2-upayments-checkout",
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Only registry reference; already in RETIRED_LEGACY_EDGE_SLUGS.",
  },
  {
    name: "verify-paypal-payment",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: ["paypal"],
    purpose: "V1 PayPal verify.",
    v2Replacement: "v2-upayments-status",
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Only registry reference.",
  },
  {
    name: "recover-orphaned-payments",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: [],
    purpose: "V1 payment cleanup.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Only registry reference.",
  },
  {
    name: "paypal-webhook",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "V1 PayPal webhook.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Live returns 410 per problem statement; source stub present.",
  },
  {
    name: "get-transaction-by-order",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: [],
    purpose: "V1 order lookup.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Only registry reference.",
  },
  {
    name: "delete-my-account",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: ["src/components/account/DeleteAccountDialog.tsx"],
    outbound: ["auth.admin"],
    purpose: "Self-service account deletion.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence:
      "Reachable from /account. verify_jwt=false but validates Bearer token in code; consider enabling platform verify_jwt.",
  },
  {
    name: "send-email",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/utils/emailService.ts",
      "src/lib/v2/admin/emailSettings.ts",
    ],
    outbound: ["resend"],
    purpose: "Transactional email sender.",
    v2Replacement: null,
    classification: "required_shared_account_auth",
    disposition: "keep",
    appliedLive: false,
    evidence: "Two active callers; signature-checked HMAC path.",
  },
  {
    name: "get-admin-transactions",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/pages/admin/components/purchases/hooks/usePurchaseHistory.ts",
    ],
    outbound: [],
    purpose: "Admin transaction listing.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "verify_jwt=false with custom verifyAdmin path; confirm verifyAdmin covers all response paths including error branches.",
  },
  {
    name: "generate-use-case",
    verifyJwt: true,
    authMechanism: "platform_jwt",
    callers: ["src/pages/admin/components/prompts/components/UseCaseField.tsx"],
    outbound: ["openai"],
    purpose: "AI: generate use-case text.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin prompt tooling.",
  },
  {
    name: "resend-confirmation-email",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "V1 email confirmation resend.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub (39 lines).",
  },
  {
    name: "auto-capture-paypal",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: ["paypal"],
    purpose: "V1 PayPal auto-capture.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Registry only.",
  },
  {
    name: "scheduled-payment-cleanup",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: [],
    purpose: "V1 payment cleanup cron.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence:
      "No pg_cron entry (only daily-security-cleanup runs); registry-only src reference.",
  },
  {
    name: "debug-environment",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "Runtime/environment introspection.",
    v2Replacement: null,
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence:
      "verify_jwt=false, no request authorization, exposes env/config. No active src caller. Confirmed retirement candidate.",
  },
  {
    name: "resend-confirmation-alternative",
    verifyJwt: true,
    authMechanism: "platform_jwt",
    callers: [],
    outbound: [],
    purpose: "Alternative signup confirmation resender.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "verify_jwt=true; no src caller. Do NOT retire without confirming no auth-form or edge-to-edge dependency.",
  },
  {
    name: "send-signup-confirmation",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "V1 signup confirmation.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub.",
  },
  {
    name: "track-email-engagement",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "Email open/click tracking.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub.",
  },
  {
    name: "enhance-prompt",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/components/enhanced-prompt/EnhancedPromptBuilder.tsx"],
    outbound: ["openai"],
    purpose: "AI: prompt enhancement.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence:
      "One active caller. verify_jwt=false; ensure bearer check is complete.",
  },
  {
    name: "send-email-confirmation-reminder",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/hooks/usePostPurchaseEmail.ts"],
    outbound: [],
    purpose: "V1 reminder emailer.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence:
      "Source is 410 stub; hook still references slug but receives 410 error.",
  },
  {
    name: "send-purchase-confirmation",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: [],
    purpose: "V1 purchase confirmation.",
    v2Replacement: "v2ReceiptDelivery (hardcoded HTML)",
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Registry only; V2 uses inline receipts.",
  },
  {
    name: "get-users-without-plans",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/useUsersWithoutPlans.ts"],
    outbound: [],
    purpose: "Admin marketing: users without active plans.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "V2 dropped subscriptions; verify admin page still uses this hook.",
  },
  {
    name: "send-bulk-plan-reminders",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/useMarketingEmails.ts"],
    outbound: ["send-email"],
    purpose: "Admin bulk plan reminders.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "V2 dropped plans; likely legacy admin marketing.",
  },
  {
    name: "send-plan-reminder",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/useMarketingEmails.ts"],
    outbound: ["send-email"],
    purpose: "Admin single plan reminder.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "Same as bulk variant.",
  },
  {
    name: "generate-magic-link",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [],
    outbound: ["auth.admin"],
    purpose: "Admin magic-link issuance.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "No src caller; may be reachable via magic-login flow.",
  },
  {
    name: "magic-login",
    verifyJwt: false,
    authMechanism: "captcha_or_rate_limit",
    callers: ["src/config/routes.ts", "src/pages/MagicLoginPage.tsx"],
    outbound: ["auth.admin"],
    purpose: "Magic-link login endpoint.",
    v2Replacement: null,
    classification: "required_shared_account_auth",
    disposition: "harden",
    appliedLive: false,
    evidence: "Route active; verify_jwt=false intentionally (pre-auth).",
  },
  {
    name: "get-user-insights",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [],
    outbound: [],
    purpose: "Admin user insights.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "No active src caller; admin page graph unclear.",
  },
  {
    name: "smart-unsubscribe",
    verifyJwt: false,
    authMechanism: "captcha_or_rate_limit",
    callers: ["src/pages/UnsubscribePage.tsx"],
    outbound: [],
    purpose: "Token-only unsubscribe.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Hardened in prior pass; token-only.",
  },
  {
    name: "ai-gpt5-metaprompt",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: ["src/components/prompt-generator/GPT5MetaPromptTab.tsx"],
    outbound: ["openai"],
    purpose: "AI: GPT-5 metaprompt.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence: "Active caller; check verify_jwt intent.",
  },
  {
    name: "ai-json-spec",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: ["src/components/prompt-generator/JsonSpecTab.tsx"],
    outbound: ["openai"],
    purpose: "AI: JSON spec generator.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence: "Active caller; check verify_jwt intent.",
  },
  {
    name: "translate-prompt",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/services/PromptService.ts"],
    outbound: ["openai"],
    purpose: "AI: bilingual prompt translation.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Hardened in prior pass.",
  },
  {
    name: "translate-text",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/components/prompt-generator/TranslationButtons.tsx",
      "src/pages/admin/components/prompts/components/BilingualFields.tsx",
    ],
    outbound: ["openai"],
    purpose: "AI: generic translation.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence: "Two callers; verify_jwt=false — enforce bearer check.",
  },
  {
    name: "auto-generate-prompt",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: [],
    outbound: ["openai"],
    purpose: "AI: prompt auto-generation.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence: "No active src caller (test-only ref).",
  },
  {
    name: "validate-signup",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/components/auth/hooks/useSignupForm.ts"],
    outbound: [],
    purpose: "V1 signup validator.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub; hook receives 410.",
  },
  {
    name: "admin-users-v2",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [],
    outbound: ["auth.admin"],
    purpose: "V2 admin user management.",
    v2Replacement: null,
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "No direct src reference found; may be invoked via generated bindings or admin V2 hook not scanned. Do NOT retire without further trace.",
  },
  {
    name: "resend-payment-email",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/pages/admin/components/users/hooks/useUserActions.ts"],
    outbound: ["send-email"],
    purpose: "Admin resend payment email.",
    v2Replacement: null,
    classification: "required_shared_account_auth",
    disposition: "keep",
    appliedLive: false,
    evidence: "Active admin caller.",
  },
  {
    name: "admin-bulk-confirm-users",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/pages/admin/components/users/hooks/useUserService.ts",
      "src/pages/admin/components/users/hooks/useUserBulkActions.ts",
    ],
    outbound: ["auth.admin"],
    purpose: "Admin bulk email confirmation.",
    v2Replacement: null,
    classification: "required_shared_account_auth",
    disposition: "keep",
    appliedLive: false,
    evidence: "Two active admin callers.",
  },
  {
    name: "check-email-exists",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "V1 email enumeration.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub.",
  },
  {
    name: "process-upayments-payment",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: ["upayments"],
    purpose: "V1 UPayments processor.",
    v2Replacement: "v2-upayments-checkout",
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Registry only.",
  },
  {
    name: "upayments-webhook",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/lib/v2/legacyEndpoints.ts"],
    outbound: [],
    purpose: "V1 UPayments webhook.",
    v2Replacement: "v2-upayments-webhook",
    classification: "legacy_unreachable",
    disposition: "retire_to_410",
    appliedLive: false,
    evidence: "Registry only; provider now targets v2-upayments-webhook.",
  },
  {
    name: "send-abandoned-cart-email",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/hooks/useAbandonedCart.ts",
      "src/pages/admin/components/abandoned-cart/AbandonedCartManagement.tsx",
    ],
    outbound: ["send-email"],
    purpose: "Abandoned cart email.",
    v2Replacement: null,
    classification: "required_shared_account_auth",
    disposition: "keep",
    appliedLive: false,
    evidence: "Two active callers.",
  },
  {
    name: "send-password-reset",
    verifyJwt: false,
    authMechanism: "none",
    callers: ["src/pages/admin/components/users/hooks/useUserService.ts"],
    outbound: [],
    purpose: "V1 custom password reset.",
    v2Replacement: "supabase.auth.resetPasswordForEmail",
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence:
      "Source is 410 stub. Admin caller path still exists but receives 410.",
  },
  {
    name: "verify-password-reset",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "V1 password reset verify.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence: "Source is 410 stub.",
  },
  {
    name: "ai-studio-chat",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/pages/admin/sections/ai-studio/AiStudioChat.tsx",
      "src/lib/v2/admin/integrationsSettings.ts",
    ],
    outbound: ["openai"],
    purpose: "Admin AI Studio chat.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Two admin callers.",
  },
  {
    name: "ai-studio-image",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/lib/v2/admin/integrationsSettings.ts"],
    outbound: ["openai"],
    purpose: "Admin AI Studio image.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin integrations probe.",
  },
  {
    name: "mcp",
    verifyJwt: false,
    authMechanism: "service_secret",
    callers: ["src/lib/v2/admin/integrationsSettings.ts"],
    outbound: [],
    purpose: "Model Context Protocol endpoint.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "harden",
    appliedLive: false,
    evidence: "One caller; validate secret guard.",
  },
  {
    name: "resource-download",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: [
      "src/hooks/v2/useResourceDownload.ts",
      "src/lib/v2/admin/storageSettings.ts",
    ],
    outbound: ["storage"],
    purpose: "V2 entitled resource download.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "V2 library download flow.",
  },
  {
    name: "admin-package-upload",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/pages/admin/sections/publishing/PackageUploader.tsx"],
    outbound: ["storage"],
    purpose: "V1 admin package upload.",
    v2Replacement: "v2-admin-upload-resource-file",
    classification: "unknown_review",
    disposition: "investigate",
    appliedLive: false,
    evidence:
      "Still called by PackageUploader; confirm whether V2 upload fully replaces it before retiring.",
  },
  {
    name: "v2-upayments-checkout",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: ["src/pages/v2/V2CheckoutPage.tsx"],
    outbound: ["upayments"],
    purpose: "V2 UPayments checkout initiation.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "V2 checkout entry point.",
  },
  {
    name: "v2-upayments-refund",
    verifyJwt: false,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminCommerce.ts"],
    outbound: ["upayments"],
    purpose: "V2 UPayments refund (admin).",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin commerce path.",
  },
  {
    name: "v2-upayments-status",
    verifyJwt: false,
    authMechanism: "platform_jwt",
    callers: [
      "src/hooks/admin/v2/useAdminCommerce.ts",
      "src/pages/v2/V2CheckoutReturnPage.tsx",
      "src/pages/v2/V2CheckoutCancelPage.tsx",
    ],
    outbound: ["upayments"],
    purpose: "V2 UPayments status polling.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Three active callers.",
  },
  {
    name: "v2-upayments-webhook",
    verifyJwt: false,
    authMechanism: "provider_signature",
    callers: ["src/components/payment/SimpleUpayButton.tsx"],
    outbound: [],
    purpose: "V2 UPayments webhook.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Provider callback; signature-verified.",
  },
  {
    name: "submit-contact",
    verifyJwt: false,
    authMechanism: "captcha_or_rate_limit",
    callers: ["src/pages/ContactPage.tsx"],
    outbound: ["send-email"],
    purpose: "Public contact form submission.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Public form; verify_jwt=false intentional.",
  },
  {
    name: "v2-admin-upload-resource-file",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/lib/v2/admin/storageSettings.ts",
      "src/pages/admin/sections/publishing/UploadPackageFile.tsx",
    ],
    outbound: ["storage"],
    purpose: "V2 admin resource upload (leasing + SHA-256).",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "V2 replacement for admin-package-upload.",
  },
  {
    name: "v2-admin-package-scan-control",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: [
      "src/lib/v2/admin/storageSettings.ts",
      "src/hooks/admin/v2/useScanProvider.ts",
    ],
    outbound: ["v2-package-scan-worker"],
    purpose: "V2 admin package scan control.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin scan controls.",
  },
  {
    name: "v2-package-scan-worker",
    verifyJwt: false,
    authMechanism: "service_secret",
    callers: ["src/lib/v2/admin/storageSettings.ts"],
    outbound: ["cloudmersive"],
    purpose: "V2 synchronous virus scan worker (Cloudmersive).",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Triggered internally by scan control.",
  },
  {
    name: "v2-qa-one-time-package-upload",
    verifyJwt: false,
    authMechanism: "none",
    callers: [],
    outbound: [],
    purpose: "QA one-shot upload harness.",
    v2Replacement: null,
    classification: "already_410",
    disposition: "keep",
    appliedLive: false,
    evidence:
      "Live returns 410 per problem statement; no source directory in this repo.",
  },
  {
    name: "v2-admin-payment-settings-status",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminPaymentSettings.ts"],
    outbound: [],
    purpose: "V2 admin payment settings dashboard.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin V2 dashboard.",
  },
  {
    name: "v2-admin-email-settings-status",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminEmailSettings.ts"],
    outbound: [],
    purpose: "V2 admin email settings dashboard.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin V2 dashboard.",
  },
  {
    name: "v2-admin-storage-settings-status",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminStorageSettings.ts"],
    outbound: [],
    purpose: "V2 admin storage settings dashboard.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin V2 dashboard.",
  },
  {
    name: "v2-admin-integrations-settings-status",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminIntegrationsSettings.ts"],
    outbound: [],
    purpose: "V2 admin integrations settings dashboard.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin V2 dashboard.",
  },
  {
    name: "v2-admin-roles-settings-status",
    verifyJwt: true,
    authMechanism: "verifyAdmin_shared",
    callers: ["src/hooks/admin/v2/useAdminRolesSettingsStatus.ts"],
    outbound: [],
    purpose: "V2 admin roles/permissions dashboard.",
    v2Replacement: null,
    classification: "required_v2",
    disposition: "keep",
    appliedLive: false,
    evidence: "Admin V2 dashboard.",
  },
] as const;

/** Bounded retirement recommendation (retire_to_410, not yet applied). */
export const RECOMMENDED_RETIREMENTS: readonly string[] = EDGE_FUNCTION_AUDIT
  .filter((e) => e.disposition === "retire_to_410")
  .map((e) => e.name);

/** Functions flagged for hardening (not retirement). */
export const RECOMMENDED_HARDENING: readonly string[] = EDGE_FUNCTION_AUDIT
  .filter((e) => e.disposition === "harden")
  .map((e) => e.name);

/** Functions requiring further investigation. */
export const REQUIRES_INVESTIGATION: readonly string[] = EDGE_FUNCTION_AUDIT
  .filter((e) => e.disposition === "investigate")
  .map((e) => e.name);
