// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-prompts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.9";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${token}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_prompts_default = defineTool({
  name: "list_my_prompts",
  title: "List my prompts",
  description: "List prompts owned by the signed-in JojoPrompts user. Returns id, title, and metadata.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of prompts to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("prompts").select("id, title, prompt_text, metadata, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${data?.length ?? 0} prompt(s).`
        }
      ],
      structuredContent: { prompts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fxkqgjakbyrxkmevkglv";
var mcp_default = defineMcp({
  name: "jojoprompts-mcp",
  title: "JojoPrompts",
  version: "0.1.0",
  instructions: "Tools for JojoPrompts. Use `list_my_prompts` to fetch prompts owned by the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_prompts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
